export const CHANGE_DRAWER = 'CHANGE_DRAWER';
export const CHANGE_PROFILE_DATA = 'CHANGE_PROFILE_DATA';
export const CHANGE_PROFILE_PIC = 'CHANGE_PROFILE_PIC';
export const CHANGE_LOGGEDIN_STATUS = 'CHANGE_LOGGEDIN_STATUS';
